#
# PodiumD Helmfile Configuration
# 
# This helmfile replaces the monolithic podiumd chart with multiple separate releases
# to avoid Kubernetes Secret size limits while maintaining the same functionality.
#

---
# Define repositories
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: wiremind
    url: https://wiremind.github.io/wiremind-helm-charts
  - name: dimpact
    url: https://Dimpact-Samenwerking.github.io/helm-charts/
  - name: maykinmedia
    url: https://maykinmedia.github.io/charts
  - name: kiss-elastic
    url: https://raw.githubusercontent.com/Klantinteractie-Servicesysteem/.github/main/docs/scripts/elastic
  - name: openshift
    url: https://charts.openshift.io
  - name: zac
    url: https://infonl.github.io/dimpact-zaakafhandelcomponent/

# Global environment configuration
environments:
  default:
    values:
      - helmfile/environments/default.yaml
  development:
    values:
      - helmfile/environments/development.yaml
  production:
    values:
      - helmfile/environments/production.yaml

---
# Component releases organized by functional groups
releases:
  #
  # Infra - Core infrastructure and platform services
  #
  - name: keycloak
    namespace: podiumd
    chart: bitnami/keycloak
    version: 24.8.0
    values:
      - helmfile/values/keycloak.yaml
    installed: false
    wait: true
    timeout: 600

  - name: clamav
    namespace: podiumd
    chart: wiremind/clamav
    version: 3.2.0
    values:
      - helmfile/values/clamav.yaml
    condition: clamav.enabled
    wait: true
    timeout: 300

  - name: infinispan
    namespace: podiumd
    chart: openshift/infinispan
    version: 0.5.0
    values:
      - helmfile/values/infinispan.yaml
    condition: infinispan.enabled
    installed: false
    needs:
      - keycloak
    wait: true
    timeout: 300

  #
  # PodiumD app - Core application components (TEMPORARILY DISABLED)
  #
  - name: openzaak
    namespace: podiumd
    chart: maykinmedia/openzaak
    version: 1.9.0
    values:
      - helmfile/values/openzaak.yaml
    condition: openzaak.enabled
    installed: false
    needs:
      - keycloak
      - clamav
    wait: true
    timeout: 600

  - name: opennotificaties
    namespace: podiumd
    chart: maykinmedia/opennotificaties
    version: 1.9.2
    values:
      - helmfile/values/opennotificaties.yaml
    condition: opennotificaties.enabled
    installed: false
    needs:
      - keycloak
    wait: true
    timeout: 300

  - name: zac
    namespace: podiumd
    chart: zac/zaakafhandelcomponent
    version: 1.0.98
    values:
      - helmfile/values/zac.yaml
    condition: zac.enabled
    installed: false
    needs:
      - openzaak
      - opennotificaties
      - keycloak
    wait: true
    timeout: 600

  - name: objecten
    namespace: podiumd
    chart: maykinmedia/objecten
    version: 2.8.1
    values:
      - helmfile/values/objecten.yaml
    condition: objecten.enabled
    installed: false
    needs:
      - keycloak
    wait: true
    timeout: 300

  - name: objecttypen
    namespace: podiumd
    chart: maykinmedia/objecttypen
    version: 1.3.3
    values:
      - helmfile/values/objecttypen.yaml
    condition: objecttypen.enabled
    installed: false
    needs:
      - keycloak
    wait: true
    timeout: 300

  - name: openarchiefbeheer
    namespace: podiumd
    chart: maykinmedia/openarchiefbeheer
    version: 1.3.10
    values:
      - helmfile/values/openarchiefbeheer.yaml
    condition: openarchiefbeheer.enabled
    installed: false
    needs:
      - keycloak
    wait: true
    timeout: 300

  - name: openklant
    namespace: podiumd
    chart: maykinmedia/openklant
    version: 1.7.0
    values:
      - helmfile/values/openklant.yaml
    condition: openklant.enabled
    installed: false
    needs:
      - keycloak
    wait: true
    timeout: 300

  - name: openformulieren
    namespace: podiumd
    chart: maykinmedia/openforms
    version: 1.8.5
    values:
      - helmfile/values/openformulieren.yaml
    condition: openformulieren.enabled
    installed: false
    needs:
      - keycloak
      - objecten
      - objecttypen
    wait: true
    timeout: 600

  - name: openinwoner
    namespace: podiumd
    chart: maykinmedia/openinwoner
    version: 1.7.5
    values:
      - helmfile/values/openinwoner.yaml
    condition: openinwoner.enabled
    installed: false
    needs:
      - keycloak
      - openzaak
      - openklant
    wait: true
    timeout: 600

  #
  # Non-prod - Testing tools, mocking and development services (TEMPORARILY DISABLED)
  #
  - name: kisselastic
    namespace: podiumd
    chart: kiss-elastic/kiss-elastic
    version: 1.0.0
    values:
      - helmfile/values/kisselastic.yaml
    condition: kisselastic.enabled
    installed: false
    wait: true
    timeout: 300

  - name: brppersonenmock
    namespace: podiumd
    chart: dimpact/brp-personen-mock
    version: 1.2.6
    values:
      - helmfile/values/brppersonenmock.yaml
    condition: brppersonenmock.enabled
    installed: false
    wait: true
    timeout: 300

# Hooks for pre/post deployment actions
hooks:
  - events: ["preSync"]
    showlogs: true
    command: "bash"
    args:
      - "-c"
      - |
        echo "🚀 Starting PodiumD deployment..."
        echo "This deployment replaces the monolithic podiumd chart with individual component releases"
        kubectl create namespace podiumd --dry-run=client -o yaml | kubectl apply -f -

  - events: ["postSync"]
    showlogs: true
    command: "bash"
    args:
      - "-c"
      - |
        echo "✅ PodiumD deployment completed successfully!"
        echo "All components have been deployed as separate Helm releases to avoid Secret size limits"
        kubectl get pods -n podiumd
