{{- if .Values.keycloak.enabled -}}
{{- if .Values.keycloak.keycloakConfigCli.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.keycloak.keycloakConfigCli.existingConfigmap }}
  labels:
    {{- include "podiumd-small.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak-config-cli
data:
  master.yaml: |
    realm: master
    attributes:
      frontendUrl: {{ .Values.keycloak.config.adminFrontendUrl | quote }}
    browserSecurityHeaders:
      xContentTypeOptions: "nosniff"
      xRobotsTag: "none"
      xFrameOptions: "SAMEORIGIN"
      contentSecurityPolicy: "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
      xXSSProtection: "1; mode=block"
      strictTransportSecurity: ""
{{- if .Values.keycloak.config.adminOtpEnabled }}
    requiredActions:
      - name: "Configure OTP"
        providerId: CONFIGURE_TOTP
        enabled: "true"
        defaultAction: "true"
        alias: CONFIGURE_TOTP
{{- end }}
{{- with .Values.keycloak.config.adminIdentityProviders }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.keycloak.config.adminIdentityProviderMappers }}
    {{- toYaml . | nindent 4 }}
{{- end }}
  realm.yaml: |
    realm: {{ .Values.keycloak.config.realm }}
    enabled: true
    displayName: {{ .Values.keycloak.config.realmDisplayName }}
    loginWithEmailAllowed: true
    rememberMe: true
    attributes:
      frontendUrl: {{ .Values.keycloak.config.realmFrontendUrl }}
      adminEventsExpiration: 10800
    browserSecurityHeaders:
      xContentTypeOptions: "nosniff"
      xRobotsTag: "none"
      xFrameOptions: "SAMEORIGIN"
      contentSecurityPolicy: "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
      xXSSProtection: "1; mode=block"
      strictTransportSecurity: ""
    requiredActions:
      - name: "Configure OTP"
        providerId: CONFIGURE_TOTP
        enabled: "true"
        defaultAction: "true"
        alias: CONFIGURE_TOTP
    clients:
      - clientId: monitoring
        name: {{ .Values.keycloak.config.clients.monitoring.name|quote }}
        enabled: {{ .Values.keycloak.config.clients.monitoring.enabled }}
        secret: {{ .Values.keycloak.config.clients.monitoring.secret|quote }}
        clientAuthenticatorType: client-secret
        redirectUris:
          - "{{ .Values.keycloak.config.clients.monitoring.oidcUrl }}/*"
        webOrigins:
          - "{{ .Values.keycloak.config.clients.monitoring.oidcUrl }}/*"
        authorizationServicesEnabled: "true"
        serviceAccountsEnabled: "true"
        protocolMappers:
          - name: "user-roles"
            protocol: "openid-connect"
            protocolMapper: "oidc-usermodel-client-role-mapper"
            consentRequired: false
            config:
              introspection.token.claim: "true"
              multivalued: "true"
              userinfo.token.claim: "false"
              user.attribute: "foo"
              id.token.claim: "true"
              lightweight.claim: "false"
              access.token.claim: "true"
              claim.name: "groups"
              jsonType.label: "String"
              usermodel.clientRoleMapping.clientId: "monitoring"
{{- if not .Values.keycloak.config.skipRoles }}
    roles:
      realm:
        - name: "admin"
          description: "Administrator role"
          composite: false
          clientRole: false
        - name: "user"
          description: "User role"
          composite: false
          clientRole: false
{{- end }}
{{- if not .Values.keycloak.config.skipGroups }}
    groups:
      - name: "Administrators"
        attributes:
          description: "Administrator group"
        subGroups:
          - name: "System Administrators"
            attributes:
              description: "System administrator group"
{{- end }}
{{- with .Values.keycloak.config.realmIdentityProviders }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.keycloak.config.realmIdentityProviderMappers }}
    {{- toYaml . | nindent 4 }}
{{- end }}
    smtp:
      starttls: {{ .Values.keycloak.config.smtp.starttls }}
      port: {{ .Values.keycloak.config.smtp.port }}
      host: {{ .Values.keycloak.config.smtp.server }}
      from: {{ .Values.keycloak.config.smtp.from }}
      fromDisplayName: {{ .Values.keycloak.config.smtp.fromDisplayName }}
      ssl: {{ .Values.keycloak.config.smtp.ssl }}
{{- end }}
{{- end }}
