apiVersion: v2
name: podiumd-small
description: PodiumD Small Helm chart (Keycloak only)
type: application
version: 4.2.1
appVersion: "4.2.1"
dependencies:
  - name: keycloak
    version: 24.8.0
    repository: "@bitnami"
    condition: keycloak.enabled
